name: Transform Updated Sources
on: workflow_dispatch
jobs:
  Transform-Updated-Sources:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Clone Transformations Repo
        uses: actions/checkout@v2
        with:
          path: transformations
      - name: Clone Sources Repo
        uses: actions/checkout@v2
        with:
          repository: cceh/c-salt_vedaweb_sources
          path: sources
      - name: Prepare Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: vw-transformations
          environment-file: transformations/environment.yml
          auto-activate-base: false
      - name: Run Transformations
        run: python transformations/transform.py sources output
      # temporary - for debugging
      - name: Publish To TEI Repo
        run: ls -lah output
