name: Transform Updated Sources
on: workflow_dispatch
jobs:
  Transform-Updated-Sources:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Clone transformations repo
        uses: actions/checkout@v2
        with:
          path: transformations
      - name: Clone sources repo
        uses: actions/checkout@v2
        with:
          repository: cceh/c-salt_vedaweb_sources
          path: sources
      - name: Clone TEI repo
        uses: actions/checkout@v2
        with:
          repository: cceh/c-salt_vedaweb_tei
          path: tei
          fetch-depth: 0
      - name: Prepare environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: vw-transformations
          environment-file: transformations/environment.yml
          auto-activate-base: false
      - name: Run transformations
        run: python transformations/transform.py $(realpath sources) $(realpath tei)
      - name: Validate transformations
        run: python transformations/validate.py $(realpath tei)
      - name: Check for diff in TEI
        run: |
          cd tei
          if ! git diff --quiet; then exit 0; else exit 1; fi
        continue-on-error: true
      - name: Push updates to TEI repo
        if: success()
        run: |
          cd tei
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "$GH_PUSH_USER"
          git add --all
          git commit -m "Apply changes made in source repo [automatic]"
          git push https://$GH_PUSH_USER:$GH_PUSH_PAM@github.com/cceh/c-salt_vedaweb_tei.git
        env:
          GH_PUSH_PAM: ${{ secrets.PAM_TEI_PUSH }}
          GH_PUSH_USER: github-actions
